### PR TITLE
story/setup-logic

### PR DESCRIPTION
**Pull request by azumari**
- Modified ProjectFelice to ProjectLiberate
- Re-established Logic Solution
- Re-established Logic.Business
- Re-established Logic.Api
- Re-established Logic.Test

Skeletal Structure is complete.
Errors remaining are due to missing pipeline.
Ready to merge with Master

### CODE REVIEW

**Comment by fredbelotte** [comment]
let me know when it is ready.

**Comment by azumari** [comment]
It has been ready to merge.
Just waiting on the merger to happen

**Comment by 7--** [comment]
Please pull

**Comment by fredbelotte** [comment]
all done.

**Pull request merged**
