### PR TITLE
Story/email and ui

### PR DESCRIPTION
**Pull request by fredbelotte**
@samchoo

### CODE REVIEW

**Comment by fredbelotte** [comment]
how goes?

**Comment by samchoo** [comment]
Made the front home page a little better.  I've been trying to get "View Batches" to work with Angular, but no luck.

**Comment by fredbelotte** [comment]
i am sure you will figure it out.

**Comment by samchoo** [comment]
Please pull to master.  

If successful you can kill this branch.  Should be because Jenkins was cool with my latest commit.

**Comment by fredbelotte** [comment]
fix the conflicts.

**Comment by samchoo** [comment]
Will do.

**Comment by samchoo** [comment]
Can you try now?

**Comment by fredbelotte** [comment]
all set!

**Pull request merged**
