### PR TITLE
story/create-forgot-password

### PR DESCRIPTION
**Pull request by tlopez92**
Created new branch. Not ready to  be merged

### CODE REVIEW

**Comment by fredbelotte** [comment]
keep it rolling!

**Comment by fredbelotte** [comment]
how is it going?

**Comment by tlopez92** [comment]
Still working on it. Getting closer but not quite there yet.

**Comment by tlopez92** [comment]
The Email sends and I can click the link now, but the link in itself is an error I'm working with

**Comment by fredbelotte** [comment]
progress... nice, i like it!

**Comment by tlopez92** [comment]
Ready to be merged to master. 
Will create a new branch from master at that point to expand upon this.

**Comment by tlopez92** [comment]
Ready to be merged

**Comment by tlopez92** [comment]
It is 100% functional now
It is ready to be merged.

**Comment by fredbelotte** [comment]
all set!

**Pull request merged**
